"""empty message

Revision ID: 5a86bb5b73d6
Revises: cace3c7e0c7c
Create Date: 2022-10-10 14:42:19.243207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a86bb5b73d6'
down_revision = 'cace3c7e0c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'date_posted')
    # ### end Alembic commands ###
